aptible/www.aptible.com

Gruntfile.js
@sandersonet for you to review/merge.
The build issue on my box was due to my local version of gems not matching what the `Gemfile.lock` asked for. Bundler will always use those versions, so I suspected that Grunt was calling ruby commands without the `bundle exec` prefix.
Turns out there is an option to configure this. I've enabled it here. My local builds run just fine now :-)
=> Use bundle exec for compass

src/partials/legal_index.hbs
@sandersonet  This, along with the corresponding frontmatter, allows us to specify the order in which Agreements appear in the legal index sidebar.
=> Use data.order to sort Agreements

src/assets/stylesheets/_price_calc.scss, src/partials/pricing_calculator.hbs
Copy changes required a few adjustments to the layout.
Additional style adjustments:
Trying some updates to the CSS opacity transitions that conflict with height transitions.
=> Pricing Calc Layout Fixes

Gruntfile.js, README.md, script/travis-deploy.sh
I accidentally deployed a copy of www to production that did not include a query plugin needed by the new technology page. I want to ensure that doesn't happen again and don't trust myself to always run the installs... so, this change is a little ham-fisted :fist:. It ensures dependencies are always installed locally by running bundle, npm, and bower installs as part of the setup, server, and deploy tasks.
What do you think @sandersonet? I'm sure there are a few other (better?) ways of achieving this. I'm new to grunt. ¯\\\_(°\_o)\_/¯
=> Always run installs to ensure dependencies are local

src/assets/stylesheets/_home.scss
Closes https://github.com/aptible/www.aptible.com/issues/142
I ended up scoping these styles to the home page (`.home`). Disappointing.
It was this or change the technology markup or remove styles on the technology console. We can go there if we need a styled console like this elsewhere.
=> Restore console styles

src/assets/stylesheets/_mobile_xs.scss
=> Fix for smaller screens getting a full viewport header

src/assets/stylesheets/_compliance.scss, src/partials/compliance_header.hbs
- Removes all content based class names
- adds some padding for testimonial copy
- removes header svgs at < 991px because it still does weird things even after removing the `hidden-sm` class
@moeamaya - I'm still seeing the SVG jank at that break point. I'm not giving up, but I'm close.
=> Compliance Adjustments

src/assets/stylesheets/_mobile_xs.scss
Currently, aptible-sass is forcing min-width to 980px for `footer.aptible-footer` (here https://github.com/aptible/aptible-sass/blob/c032609bf149e70462958a48cd71b55d6ea0c19a/dist/styles/aptible_nav.scss#L295).
This fix overrides that setting, but it may be a "quick-fix" and not the correct final solution. We should definitely confirm with @sandersonet and @gib, but we can probably deploy this for now...
=> Override desktop min-width setting for mobile.

src/assets/stylesheets/_about.scss
The career page got busted with some recent updates. I thought it was it's style classes overlapping with the new home page carousel, but that's not it.
I have another branch with more images (team in mexico!), but had to table for time.
=> Fixes the busted career image

src/assets/javascript/price_calc_state.coffee, src/assets/stylesheets/_price_calc.scss, src/partials/pricing_calculator.hbs
- Initializes the calculator at common base usage for a running app, (2
containers, 10GB DB, 1 Domain)
- DB slider is no longer linear, starting with smaller GB increments
- Call out for the $500 credit by the monthly total $ estimate and
getting started call-to-action
Closes #173 (thanks @wcpines)
=> Pricing Calculator Updates

bower.json
Closes: https://github.com/aptible/www.aptible.com/issues/179
and also resolves a potential XSS bug related to the jquery plugin:
https://github.com/alvarotrigo/fullPage.js/pull/1705
=> Fix scrolling issue on the technology page

src/partials/legal_index.hbs
@sandersonet - Any issue with using `tracked_title` in the policy/agreement frontmatter as a short version to display in the sidebar? It eliminates some redundancy.
Old:
New:
=> Use tracked_title for legal sidebar titles

src/assets/stylesheets/_product_pages.scss, src/assets/stylesheets/_support_plans.scss, src/assets/stylesheets/main.scss, src/layouts/error.hbs, src/partials/company_nav.hbs, src/partials/footer.hbs
- styles for tiered support plans page
- updated all “contact us” links to the ZD form
- removed “contact us” link from the company sub nav
Could possibly use some intro copy and @sandersonet is working on a design update (@chasballew).
Should be merged with
- https://github.com/aptible/aptible-pages/pull/66
- https://github.com/aptible/support/pull/226
=> Support Updates

src/layouts/landing-page.hbs
** Before **
** After **
@chasballew
=> Add the full footer to the landing page template

content/legal/security.md, content/pages/faq/index.hbs, content/pages/pricing/index.hbs, content/pages/technology/index.hbs, src/partials/pricing_calculator.hbs
cc @fancyremarker @gib 
This terminology change is also reflected in aptible/dashboard.aptible.com#622 and aptible/support#268
=> Use "endpoints" instead of "domains" or "vhosts"

content/legal/security.md
Explain why customers see two backups for each "Aptible Platform backed up" entry in the Activity tab.
=> Explain multiple backups

content/posts/deploy_private_images.md
How-to deploy a private Docker image on Aptible.
cc @chasballew @fancyremarker @wcpines
=> Deploy a Docker image blog post.

src/assets/stylesheets/_about.scss, src/assets/stylesheets/_blog.scss, src/assets/stylesheets/_buttons.scss, src/assets/stylesheets/_case-study.scss, src/assets/stylesheets/_compliance.scss, src/assets/stylesheets/_customers.scss, src/assets/stylesheets/_ebooks.scss, src/assets/stylesheets/_heros.scss, src/assets/stylesheets/_home.scss, src/assets/stylesheets/_landing_page.scss, src/assets/stylesheets/_layout.scss, src/assets/stylesheets/_mobile.scss, src/assets/stylesheets/main.scss
This commit sets a UTF-8 charset on the sass files, since otherwise it
will fail to compile on locales that are not using US-ASCII.
cc @gib @sandersonet
=> Set UTF-8 charset on sass files

helpers/aptible_helpers.rb, source/layouts/support-document.haml, source/stylesheets/_grid.scss, source/support/quickstart/category.haml, source/support/quickstart/index.haml
- Got the logic worked out for the breadcrumb nav and rendering language framework indexes when there are multiple framework articles for a language
- Put and "Other [Language] Frameworks" sidebar on the right, when there is one.
=> Quickstart article updates

source/blog/author.haml
@fancyremarker / @skylar: This is appears to be an issue with my understanding of setting up dynamic files. I was trying to avoid setting instance variables since those are  not available in the new version of middleman. 
https://github.com/aptible/www.aptible.com/blob/rebrand/config.rb#L82-L84
The author page I'm setting `posts` and an `author_id` for is built on its own and those are not set in that case. I'm not going to spend the time to dig in now, but if you see something, let me know.
=> Fix empty posts when a non dymanic author page is built

source/javascripts/search_page.coffee, source/partials/headers/_support-index.haml, source/partials/support/_nav-items.haml, source/stylesheets/components/_search-bar.scss, source/stylesheets/components/_swiftype-results.scss, source/support/search.haml
Still some potential turbolinks related issues, but I’ll clean those up in a separate issue. This is ready to ship.
The nav bar search input gets janky because of the CSS transition, so there is some JS gymnastics to turn off that transition and empty the input.
Closes https://github.com/aptible/www.aptible.com/issues/271
=> Make support search shippable

data/topics.yml, source/support/topics/paas/how-to-modify-nginx-config.md, source/support/topics/paas/memory-management-reference.md, source/support/topics/paas/upgrading-to-alb-endpoints.md
This adds documentation for ALB Endpoints. There are a few things that need to happen to "officially" release this feature:
cc @fancyremarker
=> Alb endpoints

source/customers/index.haml, source/enclave.haml, source/feed.xml.builder, source/gridiron.haml, source/index.haml, source/layouts/blog_post.haml, source/layouts/layout.haml, source/layouts/support-document.haml, source/partials/_nav-items.haml, source/partials/_ui-kit-header.haml, source/partials/headers/_login-signup.haml, source/partials/support/_nav-items.haml, source/pricing.haml, source/resources/index.haml, source/ui-kit/navigation.haml
@sandersonet and @shahkader identified some descrepancies in google analytics after the rebrand. I'd linked to internal pages, like `/pricing/index.html` with `/pricing` and we had been referencing `/pricing/` in analytics. Google notes this also hurts our search rank. Referenced: https://support.google.com/webmasters/answer/139066?hl=en
This chagne adds a canonical URL `link` to the page `head` and explicitly links to internal  hrefs with a trailing slash: `href=“/support/quickstart/“`
=> Canonical URLs

source/layouts/layout.haml
Thanks for catching @sandersonet
=> Major Typo for the canonical links (.___ .)

data/topics.yml, source/blog/deploy-private-images.md, source/support/topics/paas/how-to-deploy-from-private-repository.md
Instead of only having the blog post as documentation, add private
images as an actual support topic as well. This also fixes two glaring
omissions/inconsistencies with the documentation, vis-a-vis with what
the code actually does:
1) If the registry host is not docker.io (most notably images hosted
on quay.io for example), `APTIBLE_DOCKER_IMAGE` needs the registry
host specified in the image name; so instead of `my_repo/my_image` a user
needs to specify `quay.io/my_repo/my_image`.
2) If `APTIBLE_DOCKER_IMAGE` is specified, and if there's a `Dockerfile`
in the same app repo, it will be totally ignored. If you want to extend
a private image, you need to omit `APTIBLE_DOCKER_IMAGE` and just have
the `Dockerfile` extend the private image in its `FROM` clause.
cc @chasballew @fancyremarker …
=> Add a support topic for private images

source/support-plans.haml
Our Target Response Times have always been implemented in terms of business hours, not wall hours. However, that was never clearly stated (and it's also convoluted for customers to think of response times in terms of business hours). So, I've opted to use wall hour values that more closely approximate the business hour targets.
=> Clarify TRTs in wall hours, not business hours

source/legal/service-level-agreement.md
Previously, our SLA mirrored AWS in that credits were only available when an entire stack or region was down. This update makes our intent clearer, which is to provide credits when containers are affected by issues that are Aptible's fault, and a customer suffers an outage because of it.
=> Expand SLA

source/support/quickstart/php/laravel.md
See ZD #8392: it might not be entirely obvious that if you remove the
PHP MySQL SSL options, things will inevitably fail.
---
cc @fancyremarker @chasballew
=> Clarify that PHP MySQL SSL options are required

source/layouts/layout.haml, source/layouts/support-document.haml, source/stylesheets/components/_swiftype-results.scss
Right now, the entire content of the <body> section is being indexed in Swiftype as the "body" property, which is used in result summaries:
This PR updates our Swiftype meta tags to:
1. Exclude all body elements of any page by default
2. For support documents only, index the document content; exclude asides
@gib @sandersonet
=> Update support article data attributes for Swiftype

data/topics.yml, source/assets/cloudformation-redirect.json, source/support/topics/enclave/how-do-i-setup-an-apex-redirect-using-aws.md, source/support/topics/enclave/how-do-i-use-my-domain-apex-on-aptible.md, source/support/topics/enclave/how-to-add-internal-or-external-endpoint.md
This adds two articles explaining how to use domain apexes with Aptible:
- One that explains the two options we have (redirect to a subdomain, or
use the apex directly).
- One that explains how to set up a redirect from the domain apex to a
subdomain using AWS (Route 53 + CloudFormation + ACM). There's also a
CloudFormation template here to automate that set up.
---
cc @chasballew for copy
cc @fancyremarker for the template / general technical aspects of this
=> Add support articles and CFN template for apexes

Gemfile, Gemfile.lock, source/javascripts/all.js, source/javascripts/carousel.coffee, source/javascripts/nav.coffee, source/javascripts/openings.coffee, source/javascripts/search.coffee, source/javascripts/search_input.coffee, source/javascripts/search_page.coffee, source/javascripts/sticky_side_nav.coffee, source/javascripts/toolbelt.coffee, source/layouts/layout.haml, source/stylesheets/components/_header.scss, source/stylesheets/components/_nav.scss
Closes #353, #354, #373, #374, #390 
- CSS to adjust nav trigger placement
- Remove header SVG bg image grids on smaller screens (fixes screen flicker when scrolling)
- Removing Turbolinks fixes a host of issues:
- dup analytics page loads (big motivator to yank it)
- missing swiftype autocomplete menu items
- buggy nav trigger
Will discuss with @sandersonet if we want to restore Turbolinks. Reading through the docs, it could have been a lack of a `Turbolinks.start` call and/or the order that the Turbolinks js was loaded--some things to try if we decide to bring it back.
=> Removal of Turbolinks and minor CSS adjustments

source/javascripts/newsletter.coffee
Tested on staging to ensure that emails are still sent to autopilot if the form submit handler returns false… and it does.
=> Fix to ensure the newsletter signup success message is displayed

source/javascripts/newsletter.coffee, source/javascripts/notification.coffee, source/partials/_resources-aside.haml
Thanks @henryhund for finding this break. :’(
This allows the form to:
- submit, which gets the record in autopilot and reloads the page--standard html form behavior
- new JS sees the query string form submission and triggers the success flash message
- then JS replaces the location URL so subsequent reloads, back buttons, etc don't keep flashing the success message
=> Fix newsletter signup form

source/blog/hello-world.md, source/partials/_resources-footer.haml, source/stylesheets/_cards.scss, source/stylesheets/_grid.scss
The Hello World blog post had broken image references.
Fixes this issue with varying content length in the resource footer cards
Busted:
Fixed:
=> Two Bug Fixes

source/support/quickstart/ruby/rails.md, source/support/topics/enclave/how-to-set-up-bundler-caching.md
Let's try to make sure upgrades like
https://github.com/aptible/docker-ruby/pull/18 aren't as painful in
the future.
cc @fancyremarker
=> Reference specific Ruby tags

helpers/aptible_helpers.rb, source/resources/index.haml, source/support/index.haml, spec/features/blog_spec.rb, spec/features/index_spec.rb, spec/features/support_index_spec.rb
Pages under `/blog` get **POST_TITLE | Aptible Blog**
Pages under `/support` get **PAGE_TITLE | Aptible Support**
Everything else gets **TITLE | Aptible**
Added missing title to `/resources`.
=> Page title inventory + fixes with specs

data/redirects.yml, helpers/aptible_helpers.rb, source/javascripts/nav.coffee, source/partials/_footer.haml, source/partials/_main-nav.haml, source/partials/headers/_support-document.haml, source/stylesheets/components/_footer.scss, source/stylesheets/components/_nav.scss, source/support/topics/category.haml
- Added missing redirects for author pages (from `/blog/author/name.html` to `/blog/author/name/`)
- Fix support navigation bug where the email input signup CTA breaks when the user is searching for a support topic
- Moved mobile menu trigger to the upper right - suck it southpaws
- Footer links updated modified responsive...ness
=> Navigation Updates / Bug fixes

source/partials/headers/_support-document.haml, source/support/topics/category.haml
This removes the header bottom margin to get cozy with the bread crumbs from:
Back to:
=> Messed up support breadcrumbs with header change

source/support/topics/enclave/how-do-i-setup-an-apex-redirect-using-aws.md
The ACM cert we provision will otherwise not work with Cloudfront!
fyi @fancyremarker
=> Root redirect stack must be deployed in us-east-1

source/resources/resource.haml
If a resource has no `metaDescription` defined, `snippet` will be used.
=> Restored page title and description from contentful data

source/support/topics/cli/how-to-set-environment-variables.md
This adds an example for a common use case: properly escaping values that contain special characters.
=> Update the support topic for environment variables.

source/support/toolbelt.haml
The CLI reference on the website is missing a number of commands, and
this will probably continue to be the case unless it's automated.
So, this:
- Updates the reference to begin with
- Adds markers so we can automate the updates
---
cc @fancyremarker @gib
=> Update CLI commands, add markers for automation

source/stylesheets/base/_lists.scss, source/stylesheets/components/_search-bar.scss
- adjust animation speed and placement of expanding support search header input
- remove bottom padding from the last `<p>` tag in an `<li>`
The longer term fix for the `<li><p>Hello</p></li>` situation is to adjust the configuration of the markdown renderer. Looking into it.
=> Minor CSS fixes

source/support/topics/enclave/about-aptible-yml.md, source/support/topics/enclave/direct-docker-image-deploy.md, source/support/topics/enclave/dockerfile-build-deploy.md, source/support/topics/enclave/how-to-add-background-worker.md, source/support/topics/enclave/how-to-auto-restart-your-app.md, source/support/topics/enclave/how-to-deploy-app.md, source/support/topics/enclave/how-to-run-scheduled-tasks.md, source/support/topics/enclave/how-to-scale-app.md, source/support/topics/enclave/how-to-use-whenever.md, source/support/topics/enclave/private-registry-authentication.md, source/support/topics/enclave/zero-downtime-deploys.md
As it happens, relative links (which work locally) don't work in
production, which is a bit of a footgun. This updates relative links to
unbreak things for now.
=> Don't use relative links in documentation

README.md
`data.aptible` is accessed in an number of places in helpers, but that
won't work if you haven't run `middleman contentful` first.
Ideally, we probably should either handle the absence of contentful data
gracefully or crash with an explicit error, but I don't really have the
familiarity with middleman / contentful to know how that might be done.
---
cc @gib
=> Update README to mention middleman contentful

source/pricing.haml
Update Pilot Account Pricing from $1,999/mo to $3,499/mo - so when we speak to customers about pricing, we're able to provide them with a discount.
Note: The pricing update in this commit https://github.com/aptible/www.aptible.com/commit/df6f93a5115fe2f4fe668c6ee3f3cedaff2f8c32 went straight to master, but was meant for this PR.
=> Update Pilot Account Pricing

config.rb
We no longer show the most current post in the hero header. Quick fix here to get the most recent post back in the list.
=> Fix Posts Index

source/enclave.haml, source/partials/_signup-demo-request.haml, source/stylesheets/_enclave.scss, source/stylesheets/base/_typography.scss, source/stylesheets/components/_code.scss
- updates hero title and copy
- updates CTA label to “Sign Up”
- updates the copy on the list of incentives under the CTA
- fixes the mobile nav / terminal bug by hiding the terminal
- fixes an issue where adjacent `code` and fenced code blocks overlap (cc @krallin https://trello.com/c/5cdLTK2M/113-adjust-code-em-width-padding)
=> Enclave hero copy update

helpers/contentful_helpers.rb, source/blog/y-combinator.md, source/javascripts/hn_button.js, source/partials/_blog-social-share.haml, spec/fixtures/contentful/blog/introducing-direct-docker-image-deploy/input.yml, spec/fixtures/contentful/blog/introducing-direct-docker-image-deploy/output.md, spec/fixtures/contentful/blog/vulnerability-scanning-for-your-dependencies-why-and-how/output.md, spec/fixtures/contentful/changelog/managed-https-endpoints-now-support-internal-endpoints/output.md
@gib: This alters the existing override behavior a bit. Instead of providing an alternate link with which to search Algolia, I thought it would be easier, and more direct/generic to provide the desired Hacker News discussion to link to. LMK if this won't work!
=> Allow for overriding a specific Hacker News link, including via Contentful

Dockerfile, helpers/contentful_helpers.rb, script/aptible-cmd.sh, script/contentful.crontab, spec/fixtures/contentful/blog/introducing-direct-docker-image-deploy/output.md, spec/fixtures/contentful/blog/vulnerability-scanning-for-your-dependencies-why-and-how/output.md, spec/fixtures/contentful/changelog/managed-https-endpoints-now-support-internal-endpoints/output.md, spec/fixtures/contentful/learn/hipaa-compliance-for-developers-getting-started/output.md, spec/fixtures/contentful/resources/gridiron-reference-documents/output.md, spec/fixtures/contentful/resources/what-is-a-hipaa-baa/output.md, spec/fixtures/contentful/webinars/update-webinar-april-2017/_output-transcript.md, spec/fixtures/contentful/webinars/update-webinar-april-2017/output.md
Currently, we rely on Contentful Webhooks to push to Travis CI in order to be able to (a) preview Contentful changes on staging before publishing, and (b) publish Contentful changes without explicitly running a deploy. While this is [Contentful's recommended approach](https://www.contentful.com/developers/docs/ruby/tutorials/automated-rebuild-and-deploy-with-circleci-and-webhooks/), it's got a couple downsides:
1. Changes are slow to be able to preview on staging. The Travis CI build takes about 5 minutes on average, and then CloudFront caching means they may take up to an extra 5 minutes to appear on staging/production. So, it can sometimes take up to 10 minutes for a Contentful change to be visible on staging.
2. The Contentful webhook to Travis CI often fails (429 Too Many Requests), …
=> Changes to support preview.aptible.com

source/partials/_newsletter-signup--blog.haml, source/partials/_newsletter-signup.haml, source/partials/ctas/_demo-cta.haml, source/partials/ctas/_signup-cta.haml
Testing @henryhund’s theory that ad brokers are blocking our autopilot form submissions. Post forms to FormKeep where we can collect submitted emails and forward them through our tacking pipeline via zapper.
I've tested these locally, but we'll want to run through them on staging before sending to www. Given FormKeep's `_redirect_url` input and the ability to pass params on through the query string, everything works as it did previously.
=> FormKeep Forms

source/partials/_newsletter-signup--blog.haml, source/partials/_newsletter-signup.haml, source/partials/ctas/_demo-cta.haml, source/partials/ctas/_signup-cta.haml
Names forms for Autopilot via a form input, not `hidden`, that is hidden with css `display: none;`.
cc @henryhund
=> Name CTA forms for auto-pilot

source/index.haml, source/partials/_signup-demo-request.haml, source/partials/pricing/_enclave-summary.haml, source/partials/pricing/_need-more.haml, source/pricing/index.haml, source/stylesheets/_pricing.scss
This supersedes the changes in https://github.com/aptible/www.aptible.com/pull/520
This is not yet publishable. I'm still working on language, and there are some styling issues.
I made some tweaks to the changes @chasballew proposed. The biggest change I made was to the signup ctas on pricing. Please note that I'm linking the "contact us" or type ctas to http://contact.aptible.com. This is clearly not ideal given that it is a support form. However, it is the only contact page we have, and I believe, if memory serves, @shahkader is OK with receiving these types of requests through support. Hopefully, we will launch our new contact us page soon and be able to direct this type of traffic there.
This PR needs further language review before it is approved to go out. 
The styling issue that …
=> Pricing cleanup

helpers/contentful_helpers.rb, source/partials/_changelog-list-item.haml, source/stylesheets/_changelog.scss, spec/fixtures/contentful/blog/introducing-direct-docker-image-deploy/output.md, spec/fixtures/contentful/blog/vulnerability-scanning-for-your-dependencies-why-and-how/output.md, spec/fixtures/contentful/changelog/managed-https-endpoints-now-support-internal-endpoints/input.yml, spec/fixtures/contentful/changelog/managed-https-endpoints-now-support-internal-endpoints/output.md, spec/helpers/contentful_helpers_spec.rb
Two changes here:
- Added a flag in Contentful (ran this by Gib) to indicate that a given
Changelog entry's body (as opposed to its excerpt) should be rendered
in the list view. This will let us use links there, since the
Changelog entry's body is HTML.
- Removed the link surrounding each chngelog item in the index (because
that prevents us from having links in it), and replaced them with a
"Read More" link at the end.
Even though there is nothing more to read, I opted to retain the "Read
More" link for changelog posts that are displayed in full (i.e. those
that have the flag set) in the changelog index, for two reasons:
- Consistency.
- So users can access a URL for the post to share.
I'm totally to reverting that last decision, or changing the copy (e.g.
to say "to the post" instead of …
=> Allow links in the changelog index

source/aws-vs-aptible.haml, source/company/index.haml, source/enclave.haml, source/faq/index.md, source/gridiron.haml
This supersedes https://github.com/aptible/www.aptible.com/pull/512
In this pull request, I improved site language, page titles, etc. to better match our value prop and to include multiple protocols. Here's what I did:
1. Made sure none of our pages were exclusively focused on healthcare and HIPAA.
2. Improved Enclave and Gridiron page titles to optimize for display in search results and when the pages are shared, and to better capture our value prop.
3. Added the registration symbol &reg; to our Gridiron and Enclave page titles.
cc: @chasballew if you'd like to take a look at the changes, I'd be honored to hear any feedback.
@gib These are all text changes, so with your approval, I'll merge. I don't think we need to wait for @chasballew to review. If he has any feedback that we need to …
=> Updating language to clarify we are multi-protocol (and clean up page titles, etc.)

source/partials/_changelog-list-item.haml, source/stylesheets/_blog.scss, source/stylesheets/_changelog.scss, source/stylesheets/base/_typography.scss
Leverages an existing style for gridiron changelog entries by adding a product value attribute.
Fixes some missing spacing for paragraphs and adjacent lists in markdown rendered content.
=> Gridiron Changelog and markdown rendered lists

source/company/index.haml, source/stylesheets/base/_typography.scss, source/stylesheets/components/_header.scss
Hi @gib @sandersonet --
I wanted to get our new About Aptible text up quickly, with a corollary goal of slightly improving the look of our About page. I made some changes for text sizing, added in our team portrait, and centered the job postings section in the bottom.
I'm aware that the design for this about page isn't perfect, certainly isn't anywhere near @sandersonet quality. However, in an effort to improve our communication with job prospects, I wanted to get this up as quickly as possible. I'm interested in feedback and improvements, especially:
All this being said, I think the PR as it stands IS an improvement over our current About page. So I don't want to hold this up if design/CSS tweaks are going to take more than 1 business day. That is, unless you two disagree that this is an …
=> updated about page

source/layouts/resource.haml, source/stylesheets/components/_resources.scss
Resources should include documents, a contentful object type, that references PDFs that are committed to the repo.
If there is a single document, I assume it is represented by a cover image and link the image to the document as a temporary solution to our current Enclave Architecture Reference issues (see https://trello.com/c/ngDQnkPp/137-resource-cover-image-improve-ux)
The image cover image can also be removed.
=> Link resource cover images

source/partials/_nav-items.haml, source/stylesheets/_cards.scss, source/stylesheets/_customers.scss, source/stylesheets/_home.scss, source/stylesheets/bourbon/bourbon/library/_font-face.scss, source/stylesheets/components/_angled-section-dividers.scss, source/stylesheets/components/_comparison-table.scss, source/stylesheets/components/_header.scss, source/stylesheets/components/_resources.scss, source/stylesheets/enclave/_hids.scss, source/stylesheets/enclave/_index.scss
`image-url` is required to reference CSS bg images with git-ref file names. I had been referencing some without this helper.
Added a link for the Managed HIDS page.
=> Nav additions and Image URLs

helpers/contentful_helpers.rb
Linked resources are failing to sync when getting content from Contentful (a blog post’s author for example). This tries to resolve the missing entry and raises an error.
=> Address missing Contentful resources

source/javascripts/price-calculator.coffee, source/pricing/enclave.haml, source/stylesheets/components/_basic-form.scss
URL now updates to reflect the current state of the calculator. This change replaces history state for calculator value changes so the back button will return the last view, not the last price calculated.
=> Pricing Calculator - Sharable Quote

data/redirects.yml
/assets/aptible-reference-architecture.pdf => /assets/aptible-enclave-reference-architecture.pdf
=> Add redirect for reference architecture diagram

README.md, helpers/resource_helpers.rb, source/resources/index.haml
cc @henryhund 
This PR updates the /resources index to have sections, making it easier to navigate. These sections correspond with the `category` attribute in the Contentful content model for "Resources."
Because `.each_with_index` gives a fresh index, I moved the even/odd checks to start with even (i.e. 0).
@sandersonet - Specs aren't passing for me locally, something to do with the resource date specified in Contentful being in UTC-4 and my local time being in UTC-8
=> Order resources by section

source/legal/service-level-agreement.md
our markdown processor was confused, and the link on the live page is broken.
see: https://www.aptible.com/legal/service-level-agreement/
=> fix broken link in SLA

script/travis-deploy.sh
Deploying staging pulls drafts from Contentful, and then they never get
cleaned up, and they end up released to production. We don't want this:
instead, we should make sure the build environment is clean when running
a release build.
Note that since we always deploy to release by pushing the current
master branch, deploying to staging is redundant anyway.
=> Don't deploy staging on release

source/contact/sales.haml, source/enclave/hipaa-compliant-hosting.haml, source/enclave/index.haml, source/enclave/managed-host-intrusion-detection-system.haml, source/gridiron.haml, source/index.haml, source/partials/_main-nav.haml, source/partials/_newsletter-signup--blog.haml, source/partials/_newsletter-signup.haml, source/partials/ctas/_demo-cta.haml, source/partials/ctas/_easy-as-git-push.haml, source/partials/ctas/_marketing-consent.haml, source/partials/ctas/_signup-cta.haml, source/partials/pricing/_need-more.haml, source/pricing/enclave.haml, source/stylesheets/components/_marketing-consent.scss
Adds a marketing consent toggle on every signup form on the site. Also removes the "enclave in your own AWS account" language.
This branch is up on staging: https://www.aptible-staging.com/
=> Add marketing consent to all forms

source/stylesheets/base/_typography.scss
cc @henryhund 
The button is fine--the element that renders the diagonal was just over top, stealing pointer events.  This bumps the diagonals down a bit so that you can actually click the button.
=> Fix broken "Contact Aptible" button on press page

source/legal/security.md
This just copies relevant text from the marketing page into the Security Policy.
cc: @krallin
=> Update Security Policy to reference Managed HIDS

source/pricing/enclave.haml
Shared stacks are free, but the containers are not. This was confusing at least one customer.
@fancyremarker
=> Clarify stack language on pricing page

source/partials/_nav-items.haml
Adds "Aptible Resources" (`/resources/`) back into the main nav under the Resources tab.
=> Add "Aptible Resources" back into the main nav

aptiblejs/src/analytics.js, source/get/gridiron-demo.haml
This PR:
- Moves page specific javascript on the "schedule a demo" landing page into `:page_javascript`
- Removes the `drift.identify` calls from `aptible.js`, which was causing drift meeting scheduling to fail for anonymous users (not sure why this caused drift to fail, but its an edge case not worth arguing about for now)
=> Fix drift schedule a meeting links on paid landing pages

source/legal/privacy.md, source/legal/subvendor-directory.md
Make it even clearer that we don't use customer content except to provide our services, and that the BAA or data protection agreement governs in those cases. 
Also updates the subvendor directory w/ Zenprospect's new name, Apollo (not a substantive change).
=> Clarify how we restrict use of customer-provided PHI and EU personal data
