aptible/www.aptible.com

src/partials/footer.hbs
=> Use 'Quickstart' and clean up footer

src/assets/stylesheets/_about.scss, src/assets/stylesheets/_buttons.scss, src/assets/stylesheets/_mobile_md.scss
=> update employees UI to support growing number of employees"

Gruntfile.js, package.json, script/travis-deploy.sh
* Exclude READMEs from generated site
* Make all dependencies `devDependencies` and install bower as part of package.json
=> Small changes

Gruntfile.js, src/layouts/post.hbs, src/partials/post_excerpt.hbs, src/templates/blog/authors/sam.hbs
* Add a bio page (w/ posts) for Sam (this page generation should be automated, but I'm guessing that's much easier in Middleman than Assemble.io)
* Remove zeros from datestamps
=> A couple small changes

src/assets/stylesheets/_price_calc.scss
Closes https://github.com/aptible/www.aptible.com/issues/139
=> Fixes pricing content being cut off on 1000px wide viewports

src/assets/javascript/compliance.coffee, src/assets/stylesheets/_compliance.scss, src/partials/compliance_header.hbs, src/partials/header.hbs
@gib @sandersonet Let me know if you notice anything out of sorts
=> New compliance header, edited header partial, coffee file

bower.json
@gib - This updates www to use the newly minted aptible-sass without all of the script/coffeescript cruft weighing it down.
=> update aptible sass

src/partials/compliance_header.hbs
Leaving this open while we work on the compliance page copy. See aptible/aptible-pages#45
=> Compliance page copy edits

.travis.yml, README.md
cc: @chasballew @gib 
See also the following commits, which were pushed directly into the master branch of their respective repos:
* aptible/support@bc7c613
* aptible/dashboard.aptible.com@f57042b
* aptible/sheriff.aptible.com@14e6286
=> Update AWS access key and secret

src/assets/stylesheets/_blog.scss
Related to https://github.com/aptible/aptible-blog/pull/18
=> Styles tables for blog posts

src/layouts/post.hbs, src/partials/post_excerpt.hbs
Fixes https://github.com/aptible/www.aptible.com/issues/120
=> Fix blog post dates that are off by one day

src/templates/blog/authors/chas.hbs, src/templates/blog/authors/sam.hbs, src/templates/blog/index.hbs
Ensures blog post lists are sorted correctly.
Thanks for pairing on this @sandersonet!
=> Sort pages for blog post lists

src/assets/stylesheets/_mobile_sm.scss, src/assets/stylesheets/_mobile_xs.scss
Closes https://github.com/aptible/www.aptible.com/issues/88
=> Fix hidden header titles

src/assets/stylesheets/_price_calc.scss, src/assets/stylesheets/_product_pages.scss, src/partials/nav_bar.hbs
- remove “Support” from the top header nav.
- minor style adjustments for the pricing page
=> Support Clarity

src/assets/stylesheets/_pricing.scss
See https://github.com/aptible/aptible-pages/pull/67
=> Styles for revised support plan summary

src/layouts/error.hbs, src/partials/footer.hbs
=> Update contact form URL

src/assets/stylesheets/_product_pages.scss, src/partials/feature_benefits.hbs
=> Changes to product features partial to support new product page placeholders.

src/layouts/application.hbs
Depends on aptible/aptible-blog#25
=> Update blog banner for BAA post

src/assets/javascript/ebook.coffee
=> Update identified users with posted values

src/assets/stylesheets/_blog.scss
=> Constrain post images to max width of 100%

content/posts/introducing_container_metrics.md
=> Clarify how to access container metrics

content/pages/company/index.hbs, content/posts/logs_v2.md
@gib - As I mentioned, the ordering on /blog is broken for me locally. Please merge and release to prod if it looks good on your end.
@krallin - shipping your bio. Closes #214
=> Logs blog slog

content/posts/mfa.md
=> Add 2FA announcement post

content/legal/responsible_disclosure.md
=> Add security researcher hall of fame

content/legal/security.md
=> Update Security Policy

content/legal/support.md, content/pages/support/index.hbs
=> Specify normal support hours

content/posts/deploy_private_images.md
Forgot to add this in #227.
cc @wcpines @chasballew
=> Add private registry host to blog post

content/legal/privacy.md
Add more detailed information to the Privacy Shield portion of the privacy policy
=> Update to inform individuals regarding Privacy Shield practices

source/images/angle-cap.svg, source/index.haml, source/layouts/blog_post.haml, source/layouts/blog_posts.haml, source/partials/_resources-footer.haml, source/stylesheets/_cards.scss, source/stylesheets/all.css.scss, source/stylesheets/base/_variables.scss, source/stylesheets/components/_nav.scss, source/stylesheets/components/_resources-footer.scss
=> Fix Nav, Resources Footer, scaling angle cap

source/company/index.haml, source/javascripts/openings.coffee, source/stylesheets/_cards.scss, source/stylesheets/_grid.scss
- jobs from lever
- simplified header - WIP
Progress on #242
=> Company Page

helpers/aptible_helpers.rb, source/blog/index.haml, source/layouts/support-document.haml, source/partials/_resource-article.haml, source/resources/common_HIPAA_questions.md, source/resources/index.haml, source/resources/what_is_a_hipaa_baa.md, source/stylesheets/_grid.scss, source/stylesheets/all.css.scss, source/stylesheets/base/_buttons.scss, source/stylesheets/base/_lists.scss, source/stylesheets/base/_typography.scss, source/stylesheets/components/_filter.scss, source/stylesheets/components/_header.scss, source/stylesheets/components/_nav.scss, source/stylesheets/components/_resources.scss
- setup for resources like blog posts
- can list by categories (not sure how this will work dynamically… link to generated filtered pages or with JS)
- some styling
progress on #242
=> Resource index and unstyled article placeholders

content/legal/responsible_disclosure.md
=> Update RD policy with examples and video submission guidelines

config.rb, helpers/aptible_helpers.rb, source/blog/author.haml, source/layouts/blog_post.haml
=> Blog post author pages

source/support-plans.haml
=> Sections under review

source/partials/_enclave-features.haml
Figured I'd open this for review while I'm still working on "Meet the Enclave Deployment Platform" and carousel section copy.
=> First draft: Enclave Features

source/javascripts/all.js, source/javascripts/search_page.coffee, source/layouts/layout.haml
- turbolinks evaluates JS in the <head> tag only once
- remove duplicate typekit load
- install swiftype with the env key
- remove console.log
=> JS cleanup

Rakefile, data/toolbelt.yml, data/topics.yml, source/support/topics/paas/memory-management-reference.md
Merge final gap updates from support.
=> Pull in aptible/support#291 and aptible/support#292

Rakefile
This fixes our production Segment integrations by using the correct www-production source.  (This was incorrectly still using support-production)
=> Use www-production segment source

source/company/index.haml, source/customers/index.haml, source/enclave.haml, source/gridiron.haml, source/layouts/layout.haml, source/media.haml, source/support/index.haml, source/support/quickstart/index.haml, source/support/toolbelt.haml, source/support/topics/index.haml
=> Restore and add missing page titles

helpers/aptible_helpers.rb, source/pricing.haml, source/stylesheets/_grid.scss, source/stylesheets/components/_nav.scss, source/stylesheets/components/_support-pricing-tiers.scss
Closes #309
Closes #320 
Fixes the meta page-image source
=> Bug Fix Combo

source/javascripts/sticky_side_nav.coffee, source/stylesheets/base/_typography.scss, source/stylesheets/components/_nav.scss, source/stylesheets/components/_resources-footer.scss
- Fixes a dark line across the viewport above the resource footer slant
- Closes #317 - Fixes horizontal scrolling on mobile
- Closes #314 - Fixes /legal and /faq side nav positioning bugs
=> Various Fixes

spec/features/index_spec.rb, spec/features/quickstart_toc_spec.rb, spec/features/topics_toc_spec.rb, spec/shared/table_of_contents.rb, spec/shared/valid_page.rb, spec/spec_helper.rb
=> Restore support specs

config.rb, helpers/aptible_helpers.rb, helpers/blog_helpers.rb, source/blog/index.haml, source/feed.xml.builder, source/layouts/blog_post.haml, source/stylesheets/_blog.scss
Closes #329 - RSS Feed generator
Closes #316 - Footer links to previous, all, and next post(s).
=> Blog Updates

helpers/blog_helpers.rb, source/blog/index.haml, source/feed.xml.builder, source/resources/index.haml
Clarify which chronological ordering is being used
@gib @sandersonet
=> Fix ordering for previous/next blog posts

source/blog/update-webinar-oct-2016.md
=> Oct 2016 Update Webinar blog post

source/legal/breach-indemnification-agreement.md, source/legal/responsible-disclosure.md, source/legal/service-level-agreement.md
@krallin @fancyremarker - Explicitly adding email auth and user enumeration to the RD exclusions
=> Update RD policy and minor formatting fixes

source/stylesheets/base/_typography.scss
=> Add CSS style for `blockquote`s

config.rb, source/blog/database-logs.md
=> Database Logs blog post: `aptible logs` support

source/blog/cancel-running-deployments.md
@fancyremarker @chasballew ~~I used "iterate faster and safer" as the excerpt, but let me know if that's a stupid idea 😄~~
=> Add Cancel Running Deployments blog post

source/robots.txt.haml, source/sitemap.xml.haml
=> Robots.txt and Sitemap.xml Updates

spec/features/robots_spec.rb, spec/features/sitemap_spec.rb
Thanks for inspiring this find @fancyremarker: `Capybara.app.config[:base_url]`
=> Spec coverage for robots.txt and sitemap.xml

source/images/icons/windows.svg, source/stylesheets/_grid.scss, source/stylesheets/_toolbelt.scss, source/stylesheets/base/_typography.scss, source/support/toolbelt.haml
@gib - I had to hand-craft the artisanal 5 column layout since I don't think neat supports one out of the box.  Let me know if I'm mistaken or if there is a better way. 
cc @krallin
=> Add windows download panel

source/support/toolbelt.haml
This was causing windows to show up by default.
=> remove active class from windows

source/resources/update-webinar-jan-2017.md
I ran this locally to confirm it is working. Please review! Would like to get this out by 2pm EST as that is when the recap email is going to our registrants.
Sidenote: can't wait to get Contentful up and running.
=> added links to webinar resource page

source/support/topics/enclave/how-to-modify-nginx-config.md
=> Rework SSL doc, add ALB SSL_PROTOCOLS_OVERRIDE

source/partials/_resources-aside.haml, source/stylesheets/components/_newsletter-signup.scss
Makes newsletter email required
Adjusts the required input border style
=> Don't submit newsletter without an email

source/legal/security.md
=> Update database encryption info; use "Enclave"

Gemfile, config.rb, helpers/pagination_helpers.rb, source/blog/posts.haml, source/partials/_page-links.haml, source/stylesheets/_pagination.scss, source/stylesheets/all.css.scss
The middleman gem was a little trickier to work with how I'm putting together content for the blog. I'll give it another shot after putting resources into contentful.
@sandersonet -- happy to take your design direction on any changes here.
=> Blog Posts Pagination

source/resources/common-hipaa-questions.md
=> Fixed small typo in common-hipaa-questions

source/support/topics/enclave/memory-management-reference.md
=> MM no longer requires cooperative apps

source/resources/what-is-a-hipaa-baa.md
Removed trailing `-` from anchors.
=> fix toc for baa resource

source/support/topics/enclave/upgrading-to-alb-endpoints.md
=> SSL_PROTOCOLS_OVERRIDE: Fix Upgrade to ALB Docs

source/support/topics/troubleshooting/health-check-failed.md
See: https://github.com/aptible/sweetness/pull/833
cc @fancyremarker
=> Document RELEASE_HEALTHCHECK_TIMEOUT

data/topics.yml, source/support/topics/enclave/endpoint-timeouts.md
See: https://github.com/aptible/sweetness/pull/838
=> Document IDLE_TIMEOUT

source/enclave.haml, source/index.haml
changed hundreds of developers to thousands of developers.
=> updated hundreds > thousands

source/legal/terms-of-service.md, source/partials/_footer.haml
in site footer and terms of service
=> Update Company Address

source/support/topics/account/how-to-prepare-for-training.md
Updated workflow to prepare for training based on SPD updates.
=> Updated workflow based on New SPD

source/legal/security.md, source/legal/terms-of-service.md, source/partials/_footer.haml
=> Fix address and clarify scanning policy

source/partials/_signup-cta.haml
Using the browser validation with a required attribute
=> Small change to make the email required for the sign up CTA

data/topics.yml, source/support/topics/enclave/private-registry-authentication.md, source/support/topics/enclave/synchronize-deploys-and-config-changes.md
=> Add documentation for synchronized deploys

data/topics.yml, source/support/topics/enclave/about-services.md, source/support/topics/enclave/direct-docker-image-deploy.md, source/support/topics/enclave/dockerfile-build-deploy.md, source/support/topics/enclave/how-to-deploy-app.md, source/support/topics/enclave/how-to-run-scheduled-tasks.md, source/support/topics/enclave/private-registry-authentication.md, source/support/topics/enclave/synchronize-deploys-and-config-changes.md
cc: @krallin ; happy to change any of these if you disagree. For the capitalization changes, I was just trying to match convention.
=> Minor (mostly capitalization/punctuation) edits to #479

source/support/topics/cli/how-to-set-environment-variables.md, source/support/topics/enclave/how-to-access-environment-variables-inside-dockerfile.md
This was just incorrect.
cc @fancyremarker
=> .aptible.env doc updates

config.rb
=> Pagination Hotfix

source/support/topics/enclave/how-to-auto-restart-your-app.md
=> Document Container Recovery

source/faq/index.md
=> Update some FAQ copy

source/support/topics/enclave/how-to-run-scheduled-tasks.md, source/support/topics/enclave/how-to-use-whenever.md
=> Recommend Supercronic in documentation

helpers/contentful_helpers.rb, helpers/resource_helpers.rb, source/layouts/resource.haml, spec/fixtures/contentful/learn/hipaa-compliance-for-developers-getting-started/output.md, spec/fixtures/contentful/resources/gridiron-reference-documents/input.yml, spec/fixtures/contentful/resources/gridiron-reference-documents/output.md, spec/fixtures/contentful/resources/what-is-a-hipaa-baa/output.md, spec/fixtures/contentful/webinars/update-webinar-april-2017/output.md, spec/helpers/resource_helpers_spec.rb
- Sunsets contentful media attachments for resources and reference local asset paths.
- Restores webinar slides link.
- Restores missing doc type extension on resource document icons
=> Resource Documents

helpers/contentful_helpers.rb, helpers/resource_helpers.rb, source/index.haml, source/layouts/resource.haml, source/layouts/support-document.haml, source/partials/_footer.haml, source/partials/_nav-items.haml, source/partials/_resource-item.haml, source/partials/_resources-aside.haml, source/partials/headers/_featured_resource.haml, source/partials/headers/_support-document.haml, source/partials/headers/_support-index.haml, source/resources/index.haml, source/stylesheets/_blog.scss, source/stylesheets/_grid.scss, source/stylesheets/base/_variables.scss, source/stylesheets/components/_header.scss, source/stylesheets/components/_resources.scss, spec/fixtures/contentful/learn/hipaa-compliance-for-developers-getting-started/output.md, spec/fixtures/contentful/resources/gridiron-reference-documents/output.md, spec/fixtures/contentful/resources/what-is-a-hipaa-baa/output.md, spec/fixtures/contentful/webinars/update-webinar-april-2017/output.md
- updated index list page design
- new resource page design
- social links to resources pages
- featured resource and cover image to the index header
- "Read Now” hover style to index items with an image
- fix resource spec references to the hacker news url
=> Resource index and page updates

helpers/contentful_helpers.rb
It's hard to tell exactly where the exception is coming from, otherwise.
=> Log contentful error backtraces

source/legal/security.md
@krallin - To go with aptible/docs/pull/24
=> Reference docs in data retention section of Security Policy

source/partials/_nav-items.haml, source/stylesheets/components/_nav.scss
=> Update pricing link copy and style

helpers/aptible_helpers.rb, source/blog/aws-webinar-06-2015.md, source/blog/most-popular-databases.md, source/changelog/deploy-private-images.md, source/changelog/introducing-container-metrics.md, source/changelog/logs-v2.md, source/changelog/managed-https.md, source/changelog/mfa.md, source/contact/index.haml, source/partials/pricing/_need-more.haml, source/pricing/index.haml
Send all links to `/contact/` or `/contact/sales/`
=> Update contact links

source/enclave.haml, source/partials/_developers-first.haml, source/stylesheets/_enclave.scss, source/stylesheets/components/_code.scss, source/stylesheets/components/_enclave-carousel.scss
- Add named compliance frameworks to the page subtitle
- Fix learn more links
- Remove last AWS comparison item
- link developer guides
- SVG carousel responsive adjustments
=> Enclave Cleanup

source/partials/_footer.haml, source/partials/_nav-items.haml, source/stylesheets/components/_footer.scss
- Add HIPAA Cloud to Products > Solutions
- Add Solutions section to footer nav
- Responsive adjustments to footer nav
=> Nav Adjustments

source/layouts/resource.haml, source/resources/index.haml, source/stylesheets/components/_newsletter-signup.scss, source/stylesheets/components/_resources.scss
=> Add newsletter CTA to resources index and resource docs

source/javascripts/price-calculator.coffee, source/partials/pricing/_enclave-summary.haml, source/pricing/enclave.haml, source/stylesheets/components/_basic-form.scss, source/stylesheets/components/_pricing-calculator.scss, source/ui-kit/index.haml
@gib: This is purely a proof-of-concept for how we might incorporate Managed HIDS into the Pricing Calculator (not intending for merge yet). Can I review this with you tomorrow to determine where to take it from here?
Probably best tested live at https://preview.aptible.com/pricing/enclave
=> Proof-of-concept: adding Managed HIDS to Pricing Calculator

source/contact/sales.haml, source/enclave/index.haml, source/partials/_footer.haml, source/partials/_nav-items.haml, source/sign-up.haml, source/stylesheets/components/_contact-sales.scss, source/stylesheets/components/_footer.scss
- Adds the marketing sign-up form
- Match HIDS links and page title
- adjust footer line height for links that span multiple lines
- Contact Sales Form Updates
- Split First and Last name to separate inputs.
- Keep checkbox label on a single line
=> Marketing Sign-up Form

source/legal/responsible-disclosure.md
=> Update HOF and clarify some scope

source/partials/_footer.haml
Update footer to say "2018" instead of 2017.
=> 2017 > 2018

config.rb, source/layouts/layout.haml
=> Add clearbit GA plugin

source/contact/sales.haml, source/javascripts/notification.coffee, source/stylesheets/enclave/_index.scss
- Fixes sub nav overflow hidden bug
- Contact sales form updates
- success message
- posts the products to schedule a demo
=> Minor fixes

source/javascripts/contact-form.coffee
- adds segment event
- prevents submission of the demo product names if the checkbox is not checked
=> Contact Sales form submit handler

source/layouts/post.haml, source/stylesheets/_blog.scss
New on the left 👶 , old on the right 👴
=> Give blog post text more space on mobile

source/index.haml
@chasballew requested an update to the quote on the homepage cc @henryhund
=> Update homepage quote

data/team.yml
=> Bio update

helpers/resource_helpers.rb, source/layouts/layout.haml, source/resources/index.haml
Adds the webinars category to the resources page, also removes the clearbit javascript.
cc @henryhund
=> Add webinars to resources page

source/stylesheets/components/_marketing-consent.scss
Quick css fix for marketing consent fields.
=> Make sure consent fields show above gradients

source/legal/responsible-disclosure.md
=> Bug Bounty: Clarify rate limits are out of scope

source/stylesheets/_compliance.scss
Fixes mobile CSS issue on HIPAA BAA page (#616)
=> Fix text wrap in pre tag

signupjs/src/components/container/SignupWizard.js, source/layouts/gridiron2_adwords.haml, source/layouts/layout.haml, source/partials/gridiron2/_testimonial-vergesense.haml, source/signup/index.haml, source/signup/thank-you.haml, source/stylesheets/_gridiron2.scss, source/stylesheets/_signup.scss
Adds adwords conversion tracking once visitors enter their email on the new Gridiron signup flow, and css fixes for mobile devices.
=> Adwords conversion tracking, mobile fixes

source/legal/security.md
@fancyremarker This bumps the version and adds some language around our own pen testing (a customer asked about this today, and we receive questions about it periodically)
cc @michaelscottlyons @krallin
=> Add pen testing info

source/company/index.haml
Adds mission and values.
@mjp I inlined a couple of layout adjustments so as to minimize any possible css conflicts.  This content is likely to change soon, we can revisit the design once content is more stable.
=> Company content updates

source/company/index.haml
=> over => Over

aptiblejs/src/analytics.js, aptiblejs/src/cookie-consent.js, signupjs/src/components/container/ProductSelection.js, signupjs/src/components/container/SignupWizard.js, source/get/enterprise-sales.haml, source/gridiron/index.haml, source/hipaa/what-is-a-baa.haml, source/javascripts/cta-analytics.js, source/javascripts/drift.js, source/layouts/gridiron2_adwords.haml, source/partials/_newsletter-signup--blog.haml, source/partials/_newsletter-signup.haml, source/partials/ctas/_signup-cta.haml, source/partials/gridiron2/_bottom-cta-newsletter.haml, source/partials/gridiron2/_sticky-nav-gridiron.haml, source/stylesheets/_compliance.scss
Adds:
- Standardized event names, and event tracking on all CTAs
- New / improved integration with google ad, quora ad tracking
- New CTA on the HIPAA BAA page, and line height fix
- New adwords landing page
=> Analytics on CTAs

aptiblejs/src/analytics.js, signupjs/src/components/container/SignupWizard.js, source/javascripts/cta-analytics.js, source/layouts/gridiron2_adwords.haml, source/layouts/layout.haml, source/signup/index.haml
This PR:
- Moves the quora ads pixel outside of Segment (which did not support page view tracking) and into the main layout (for collecting a retargeting audience)
- Adds some error checking around sending analytics events and preventing exceptions to occur
=> Analytics improvements

signupjs/src/components/container/Customize.js, signupjs/src/components/container/Email.js, signupjs/src/components/container/HowHeard.js, signupjs/src/components/container/ProductSelection.js, signupjs/src/components/container/Profile.js, signupjs/src/components/container/SignupWizard.js, source/enclave/hipaa-compliant-hosting.haml, source/enclave/index.haml, source/enclave/managed-host-intrusion-detection-system.haml, source/gridiron/index.haml
This PR:
- Fixes an issue with analytics event naming where a react component `.name` was returning `t` instead of its full name after being minified.
- Changes the meta title and description for the Gridiron page.
=> Signup analytics & gridiron meta tags
